name: Java CI with Maven

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -U
      - name: Move the package
        run: mkdir artifact && cp target/*.jar artifact
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: artifact/

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: target/

      - name: Deploy to server
        run: |
          # Use the "target/" directory from Job 1 as the input for Job 2
          # scp -r target/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html/
          

  Run-Caesar-Tests:

    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Run Caesar Tests
        run: echo "Testing"



