name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

   

    - name: Store Test Results
      run: |
        echo "Hello World" > result
        mkdir -p $HOME/test-results/$(date +%Y-%m-%d_%H-%M-%S)
        cp  result $HOME/test-results/$(date +%Y-%m-%d_%H-%M-%S)/
      shell: bash

    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: $HOME/test-results

    - name: Create Deployment Status
      run: |
        curl -s -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.ant-man-preview+json" \
          -H "Content-Type: application/json" \
          -d "{\"state\": \"success\", \"target_url\": \"https://github.com/${{ github.repository }}/actions/artifacts/${{ job.outputs.artifact_id }}/zip\", \"description\": \"Test results available at https://github.com/${{ github.repository }}/actions/artifacts/${{ job.outputs.artifact_id }}/zip\", \"environment\": \"production\"}" \
          "https://api.github.com/repos/${{ github.repository }}/deployments/${{ github.run_id }}/statuses"
      env:
        ARTIFACT_ID: ${{ steps.upload-test-results.outputs.artifact_id }}



